# create service mongodb ke port : 27017
apiVersion: v1
kind: Service
metadata:
  name: mongo-db
  labels:
    app: mongo-db
    tier: database
spec:
  clusterIP: None
  selector:
    app: mongo-db
    tier: database
  ports:
  - port: 27017