apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-service
  labels:
    app: shipping-service
    tier: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping-service
      tier: consumer
  template:
    metadata:
      labels:
        app: shipping-service
        tier: consumer
    spec:
      containers:
      # Ambil dari GCHR yang sudah dibuild pada branch order-service
      - name: shipping-service
        image: ghcr.io/fadlincode/ecommerce-shipping-service:latest
        ports:
        - containerPort: 3001
        env:
        # Ambil password dari secret rabbitmq 
        - name: AMQP_PASSWORD  
          valueFrom:
            secretKeyRef:
              name: rabbitmq
              key: rabbitmq-password
        - name: AMQP_URL
          value: "amqp://user:$(AMQP_PASSWORD)@rabbitmq:5672/"